# Generated by Django 5.0.1 on 2025-01-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='cost_per_item',
            new_name='cost',
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='publisher',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
