# Generated by Django 5.0.1 on 2025-03-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_cost_per_item_inventory_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='item_code',
            field=models.CharField(default='', max_length=25),
        ),
    ]
